# Generated by Django 5.1.2 on 2024-10-23 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
    ]
